### ISSUE TITLE
Cannot access request header fields after connection is set

### ISSUE THREAD

**Issue by saletrak** [feelfreelinux/WykopMobilny#22]
Error appears while loading content mostly after new loging to the app.

![screenshot_4](https://user-images.githubusercontent.com/20685933/30123357-07c21932-9332-11e7-8edc-69aa7ecba267.png)

```
java.lang.IllegalStateException: Cannot access request header fields after connection is set
     at com.github.kittinunf.fuel.toolbox.HttpClient.executeRequest(HttpClient.kt:69)
     at com.github.kittinunf.fuel.core.requests.TaskRequest.call(TaskRequest.kt:16)
     at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:13)
     at com.github.kittinunf.fuel.core.requests.AsyncTaskRequest.call(AsyncTaskRequest.kt:6)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
     at com.github.kittinunf.fuel.core.FuelManager$executor$2$1$1.run(FuelManager.kt:49)
     at java.lang.Thread.run(Thread.java:764)
```

**Comment by feelfreelinux** [comment]
Newest commit ported the app to retrofit, so this issue should be fixed now,
